cons: add comment about sheet name type
mypy gives the following type error if this seemingly redundant mapping
isn't done:

```
src/odm_sharing/private/cons.py:50: error: Argument 2 to
"_write_table_to_db" has incompatible type "Union[int, str]"; expected
"str"  [arg-type]
```

It seems like sheet_name may be an integer as well as a string, so it's
best to map all names to string.